export const ADD_TODO = 'ADD_TODO';
export const UPLOAD_TODO_FROM_LOCAL_STORAGE = 'UPLOAD_TODO_FROM_LOCAL_STORAGE';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const EDIT_STATUS = 'EDIT_STATUS';
export const CLOSE_DIALOG_ADD = 'CLOSE_DIALOG_ADD';
export const OPEN_DIALOG_ADD = 'OPEN_DIALOG_ADD';
export const OPEN_DIALOG_EDIT = 'OPEN_DIALOG_EDIT';
export const CLOSE_DIALOG_EDIT = 'CLOSE_DIALOG_EDIT';
export const OPEN_ALERT_TO_CONFIRM = 'OPEN_ALERT_TO_CONFIRM';
export const CLOSE_ALERT_TO_CONFIRM = 'CLOSE_ALERT_TO_CONFIRM';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const UPDATE_FILTERED_TASKS = 'UPDATE_FILTERED_TASKS';
export const CLEAR_SEARCH_VALUE = 'CLEAR_SEARCH_VALUE';
export const UPLOAD_CASHED_TASKS = 'UPLOAD_CASHED_TASKS';

